=== UJTWLL/UJTWLL_XMLGyak/UJTWLL_0929/FM_konyv.dtd
<!ELEMENT konyvek (konyv)>
<!ELEMENT konyv (cim, kiadas, kiado, id, szerzo+, absztrakt?)>
<!ATTLIST konyv id CDATA #REQUIRED>
<!ELEMENT cim (#PCDATA)>
<!ELEMENT kiadas (#PCDATA)>
<!ELEMENT kiado (#PCDATA)>
<!ELEMENT szerzo (#PCDATA)>
<!ELEMENT absztrakt (#PCDATA)>

=== UJTWLL/UJTWLL_XMLGyak/UJTWLL_0929/FM_konyv.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE konyvek SYSTEM "FM_konyv.dtd">

<konyvek>
    <konyv id="58">
        <cim>C biblia</cim>
        <kiadas>2010</kiadas>
        <kiado>Mozaik</kiado>
        <szerzo>Moe Lester</szerzo>
    </konyv>
    <konyv id="21">
        <cim>Szövegbányászat és mesterséges intelligencia</cim>
        <kiadas>2016</kiadas>
        <kiado>Bookline</kiado>
        <szerzo>Sebők Miklós</szerzo>
        <szerzo>Ring Orsolya</szerzo>
        <szerzo>Máté Ákos</szerzo>
    </konyv>
    <konyv id="83">
        <cim>Java</cim>
        <kiadas>2010</kiadas>
        <kiado>Booknet</kiado>
        <szerzo>Barry Burd</szerzo>
    </konyv>
<konyvek>
