=== UJTWLL/UJTWLL_XMLGyak/UJTWLL_1013/FM_nevjegykartya.xsd
<?xml version="1.0" encoding="utf-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:simpleType name="irszTipus">
    <xs:restriction base="xs:integer">
        <xs:pattern value="[1-9][0-9]{3}"/>
    </xs:restriction>
</xs:simpleType>
    
<xs:simpleType name="nevTipus">
    <xs:restriction base="xs:string">
        <xs:minLength value="2"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="hszTipus">
    <xs:restriction base="xs:integer">
        <xs:minInclusive value="1"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="telTipus">
    <xs:restriction base="xs:integer">
        <xs:pattern value="06[0-9]{7}"/>
        <xs:pattern value="06[0-9]{8}"/>
        <xs:pattern value="06[0-9]{9}"/>
    </xs:restriction>
</xs:simpleType>

    <xs:element name="nevjegykartyak">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nevjegykartya" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nev" type="xs:string"/>
                            <xs:element name="ceg">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nev" type="xs:string"/>
                                        <xs:element name="cim">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="irsz" type="irszTipus"/>
                                                    <xs:element name="varos" type="nevTipus"/>
                                                    <xs:element name="utca" type="nevTipus"/>
                                                    <xs:element name="hsz" type="hszTipus"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="tel" type="telTipus"/>
                                        <xs:element name="weblap" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:integer" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== UJTWLL/UJTWLL_XMLGyak/UJTWLL_1013/FM_nevjegykartya.xml
<?xml version="1.0" encoding="utf-8"?>

<nevjegykartyak xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FM_nevjegykartya.xsd">
	<nevjegykartya id="1">
		<nev>Ferencsik Márk</nev>
		<ceg>
			<nev>simpleSoft Kft.</nev>
			<cim>
				<irsz>3525</irsz>
				<varos>Miskolc</varos>
				<utca>Szentpáli</utca>
				<hsz>1</hsz>
			</cim>
			<tel>0646740640</tel>
			<weblap>https://simplesoft.hu/</weblap>
		</ceg>
	</nevjegykartya>
	<nevjegykartya id="2">
		<nev>Kokeró Károly</nev>
		<ceg>
			<nev>evoSoft Hungary Kft.</nev>
			<cim>
				<irsz>3525</irsz>
				<varos>Miskolc</varos>
				<utca>Arany János</utca>
				<hsz>1</hsz>
			</cim>
			<tel>0646501120</tel>
			<weblap>https://www.evosoft.hu/</weblap>
		</ceg>
	</nevjegykartya>
</nevjegykartyak>
